---
- name: install Apache webserver
  slackpkg: name=httpd state=present
  notify:
    - restart apache

- name: create configuration directories
  file: path="{{ item }}" owner=root group=root mode=0755 state=directory
  with_items:
    - /etc/httpd/domains
    - /etc/httpd/sites
  notify:
    - restart apache

- name: add Apache ssl.conf file
  template: src=ssl.conf.j2 dest=/etc/httpd/ssl.conf owner=root group=root mode=0644
  when: apache_ssl_enabled
  notify:
    - restart apache

- name: add ssl.conf configuration include
  blockinfile:
    dest: /etc/httpd/httpd.conf
    marker: "# {mark} ANSIBLE MANAGED 'SSL' BLOCK"
    validate: "/usr/sbin/httpd -S -f %s"
    content: "Include /etc/httpd/ssl.conf"
  when: apache_ssl_enabled
  notify:
    - restart apache

- name: add sites configuration include
  blockinfile:
    dest: /etc/httpd/httpd.conf
    marker: "# {mark} ANSIBLE MANAGED 'SITES' BLOCK"
    validate: "/usr/sbin/httpd -S -f %s"
    content: "IncludeOptional /etc/httpd/sites/*.conf"
  notify:
    - restart apache

- name: enable Apache autostart
  file: path=/etc/rc.d/rc.httpd mode=0755
  when: apache_autostart

